// source: bilibili/app/archive/v1/archive.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = self;

goog.exportSymbol('proto.bilibili.app.archive.v1.Arc', null, global);
goog.exportSymbol('proto.bilibili.app.archive.v1.Author', null, global);
goog.exportSymbol('proto.bilibili.app.archive.v1.Dimension', null, global);
goog.exportSymbol('proto.bilibili.app.archive.v1.Page', null, global);
goog.exportSymbol('proto.bilibili.app.archive.v1.Rights', null, global);
goog.exportSymbol('proto.bilibili.app.archive.v1.StaffInfo', null, global);
goog.exportSymbol('proto.bilibili.app.archive.v1.Stat', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.archive.v1.Arc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bilibili.app.archive.v1.Arc.repeatedFields_, null);
};
goog.inherits(proto.bilibili.app.archive.v1.Arc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.archive.v1.Arc.displayName = 'proto.bilibili.app.archive.v1.Arc';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.archive.v1.Author = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.archive.v1.Author, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.archive.v1.Author.displayName = 'proto.bilibili.app.archive.v1.Author';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.archive.v1.Dimension = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.archive.v1.Dimension, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.archive.v1.Dimension.displayName = 'proto.bilibili.app.archive.v1.Dimension';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.archive.v1.Page = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.archive.v1.Page, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.archive.v1.Page.displayName = 'proto.bilibili.app.archive.v1.Page';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.archive.v1.Rights = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.archive.v1.Rights, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.archive.v1.Rights.displayName = 'proto.bilibili.app.archive.v1.Rights';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.archive.v1.StaffInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.archive.v1.StaffInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.archive.v1.StaffInfo.displayName = 'proto.bilibili.app.archive.v1.StaffInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.archive.v1.Stat = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.archive.v1.Stat, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.archive.v1.Stat.displayName = 'proto.bilibili.app.archive.v1.Stat';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bilibili.app.archive.v1.Arc.repeatedFields_ = [15,28];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.archive.v1.Arc.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.archive.v1.Arc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.archive.v1.Arc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Arc.toObject = function(includeInstance, msg) {
  var f, obj = {
    aid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    videos: jspb.Message.getFieldWithDefault(msg, 2, 0),
    typeId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    typeName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    copyright: jspb.Message.getFieldWithDefault(msg, 5, 0),
    pic: jspb.Message.getFieldWithDefault(msg, 6, ""),
    title: jspb.Message.getFieldWithDefault(msg, 7, ""),
    pubdate: jspb.Message.getFieldWithDefault(msg, 8, 0),
    ctime: jspb.Message.getFieldWithDefault(msg, 9, 0),
    desc: jspb.Message.getFieldWithDefault(msg, 10, ""),
    state: jspb.Message.getFieldWithDefault(msg, 11, 0),
    access: jspb.Message.getFieldWithDefault(msg, 12, 0),
    attribute: jspb.Message.getFieldWithDefault(msg, 13, 0),
    tag: jspb.Message.getFieldWithDefault(msg, 14, ""),
    tagsList: (f = jspb.Message.getRepeatedField(msg, 15)) == null ? undefined : f,
    duration: jspb.Message.getFieldWithDefault(msg, 16, 0),
    missionId: jspb.Message.getFieldWithDefault(msg, 17, 0),
    orderId: jspb.Message.getFieldWithDefault(msg, 18, 0),
    redirectUrl: jspb.Message.getFieldWithDefault(msg, 19, ""),
    forward: jspb.Message.getFieldWithDefault(msg, 20, 0),
    rights: (f = msg.getRights()) && proto.bilibili.app.archive.v1.Rights.toObject(includeInstance, f),
    author: (f = msg.getAuthor()) && proto.bilibili.app.archive.v1.Author.toObject(includeInstance, f),
    stat: (f = msg.getStat()) && proto.bilibili.app.archive.v1.Stat.toObject(includeInstance, f),
    reportResult: jspb.Message.getFieldWithDefault(msg, 24, ""),
    dynamic: jspb.Message.getFieldWithDefault(msg, 25, ""),
    firstCid: jspb.Message.getFieldWithDefault(msg, 26, 0),
    dimension: (f = msg.getDimension()) && proto.bilibili.app.archive.v1.Dimension.toObject(includeInstance, f),
    staffInfoList: jspb.Message.toObjectList(msg.getStaffInfoList(),
    proto.bilibili.app.archive.v1.StaffInfo.toObject, includeInstance),
    seasonId: jspb.Message.getFieldWithDefault(msg, 29, 0),
    attributeV2: jspb.Message.getFieldWithDefault(msg, 30, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.archive.v1.Arc}
 */
proto.bilibili.app.archive.v1.Arc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.archive.v1.Arc;
  return proto.bilibili.app.archive.v1.Arc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.archive.v1.Arc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.archive.v1.Arc}
 */
proto.bilibili.app.archive.v1.Arc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setVideos(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTypeId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTypeName(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCopyright(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPic(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPubdate(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCtime(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDesc(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setState(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAccess(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAttribute(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDuration(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMissionId(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOrderId(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedirectUrl(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setForward(value);
      break;
    case 21:
      var value = new proto.bilibili.app.archive.v1.Rights;
      reader.readMessage(value,proto.bilibili.app.archive.v1.Rights.deserializeBinaryFromReader);
      msg.setRights(value);
      break;
    case 22:
      var value = new proto.bilibili.app.archive.v1.Author;
      reader.readMessage(value,proto.bilibili.app.archive.v1.Author.deserializeBinaryFromReader);
      msg.setAuthor(value);
      break;
    case 23:
      var value = new proto.bilibili.app.archive.v1.Stat;
      reader.readMessage(value,proto.bilibili.app.archive.v1.Stat.deserializeBinaryFromReader);
      msg.setStat(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setReportResult(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.setDynamic(value);
      break;
    case 26:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFirstCid(value);
      break;
    case 27:
      var value = new proto.bilibili.app.archive.v1.Dimension;
      reader.readMessage(value,proto.bilibili.app.archive.v1.Dimension.deserializeBinaryFromReader);
      msg.setDimension(value);
      break;
    case 28:
      var value = new proto.bilibili.app.archive.v1.StaffInfo;
      reader.readMessage(value,proto.bilibili.app.archive.v1.StaffInfo.deserializeBinaryFromReader);
      msg.addStaffInfo(value);
      break;
    case 29:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSeasonId(value);
      break;
    case 30:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAttributeV2(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.archive.v1.Arc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.archive.v1.Arc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.archive.v1.Arc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Arc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getVideos();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getTypeId();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getTypeName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCopyright();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getPic();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPubdate();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getCtime();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getDesc();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getState();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getAccess();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getAttribute();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      15,
      f
    );
  }
  f = message.getDuration();
  if (f !== 0) {
    writer.writeInt64(
      16,
      f
    );
  }
  f = message.getMissionId();
  if (f !== 0) {
    writer.writeInt64(
      17,
      f
    );
  }
  f = message.getOrderId();
  if (f !== 0) {
    writer.writeInt64(
      18,
      f
    );
  }
  f = message.getRedirectUrl();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getForward();
  if (f !== 0) {
    writer.writeInt64(
      20,
      f
    );
  }
  f = message.getRights();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      proto.bilibili.app.archive.v1.Rights.serializeBinaryToWriter
    );
  }
  f = message.getAuthor();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      proto.bilibili.app.archive.v1.Author.serializeBinaryToWriter
    );
  }
  f = message.getStat();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      proto.bilibili.app.archive.v1.Stat.serializeBinaryToWriter
    );
  }
  f = message.getReportResult();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
  f = message.getDynamic();
  if (f.length > 0) {
    writer.writeString(
      25,
      f
    );
  }
  f = message.getFirstCid();
  if (f !== 0) {
    writer.writeInt64(
      26,
      f
    );
  }
  f = message.getDimension();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      proto.bilibili.app.archive.v1.Dimension.serializeBinaryToWriter
    );
  }
  f = message.getStaffInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      28,
      f,
      proto.bilibili.app.archive.v1.StaffInfo.serializeBinaryToWriter
    );
  }
  f = message.getSeasonId();
  if (f !== 0) {
    writer.writeInt64(
      29,
      f
    );
  }
  f = message.getAttributeV2();
  if (f !== 0) {
    writer.writeInt64(
      30,
      f
    );
  }
};


/**
 * optional int64 aid = 1;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getAid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setAid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 videos = 2;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getVideos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setVideos = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 type_id = 3;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getTypeId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setTypeId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string type_name = 4;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getTypeName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setTypeName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 copyright = 5;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getCopyright = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setCopyright = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string pic = 6;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getPic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setPic = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string title = 7;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int64 pubdate = 8;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getPubdate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setPubdate = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 ctime = 9;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getCtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setCtime = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string desc = 10;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getDesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setDesc = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional int32 state = 11;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getState = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setState = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 access = 12;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getAccess = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setAccess = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int32 attribute = 13;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getAttribute = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setAttribute = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional string tag = 14;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setTag = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * repeated string tags = 15;
 * @return {!Array<string>}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 15));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setTagsList = function(value) {
  return jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.addTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.clearTagsList = function() {
  return this.setTagsList([]);
};


/**
 * optional int64 duration = 16;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getDuration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setDuration = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional int64 mission_id = 17;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getMissionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setMissionId = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * optional int64 order_id = 18;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getOrderId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setOrderId = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional string redirect_url = 19;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getRedirectUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setRedirectUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional int64 forward = 20;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getForward = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setForward = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional Rights rights = 21;
 * @return {?proto.bilibili.app.archive.v1.Rights}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getRights = function() {
  return /** @type{?proto.bilibili.app.archive.v1.Rights} */ (
    jspb.Message.getWrapperField(this, proto.bilibili.app.archive.v1.Rights, 21));
};


/**
 * @param {?proto.bilibili.app.archive.v1.Rights|undefined} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
*/
proto.bilibili.app.archive.v1.Arc.prototype.setRights = function(value) {
  return jspb.Message.setWrapperField(this, 21, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.clearRights = function() {
  return this.setRights(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bilibili.app.archive.v1.Arc.prototype.hasRights = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional Author author = 22;
 * @return {?proto.bilibili.app.archive.v1.Author}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getAuthor = function() {
  return /** @type{?proto.bilibili.app.archive.v1.Author} */ (
    jspb.Message.getWrapperField(this, proto.bilibili.app.archive.v1.Author, 22));
};


/**
 * @param {?proto.bilibili.app.archive.v1.Author|undefined} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
*/
proto.bilibili.app.archive.v1.Arc.prototype.setAuthor = function(value) {
  return jspb.Message.setWrapperField(this, 22, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.clearAuthor = function() {
  return this.setAuthor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bilibili.app.archive.v1.Arc.prototype.hasAuthor = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional Stat stat = 23;
 * @return {?proto.bilibili.app.archive.v1.Stat}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getStat = function() {
  return /** @type{?proto.bilibili.app.archive.v1.Stat} */ (
    jspb.Message.getWrapperField(this, proto.bilibili.app.archive.v1.Stat, 23));
};


/**
 * @param {?proto.bilibili.app.archive.v1.Stat|undefined} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
*/
proto.bilibili.app.archive.v1.Arc.prototype.setStat = function(value) {
  return jspb.Message.setWrapperField(this, 23, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.clearStat = function() {
  return this.setStat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bilibili.app.archive.v1.Arc.prototype.hasStat = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional string report_result = 24;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getReportResult = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setReportResult = function(value) {
  return jspb.Message.setProto3StringField(this, 24, value);
};


/**
 * optional string dynamic = 25;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getDynamic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 25, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setDynamic = function(value) {
  return jspb.Message.setProto3StringField(this, 25, value);
};


/**
 * optional int64 first_cid = 26;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getFirstCid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 26, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setFirstCid = function(value) {
  return jspb.Message.setProto3IntField(this, 26, value);
};


/**
 * optional Dimension dimension = 27;
 * @return {?proto.bilibili.app.archive.v1.Dimension}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getDimension = function() {
  return /** @type{?proto.bilibili.app.archive.v1.Dimension} */ (
    jspb.Message.getWrapperField(this, proto.bilibili.app.archive.v1.Dimension, 27));
};


/**
 * @param {?proto.bilibili.app.archive.v1.Dimension|undefined} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
*/
proto.bilibili.app.archive.v1.Arc.prototype.setDimension = function(value) {
  return jspb.Message.setWrapperField(this, 27, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.clearDimension = function() {
  return this.setDimension(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bilibili.app.archive.v1.Arc.prototype.hasDimension = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * repeated StaffInfo staff_info = 28;
 * @return {!Array<!proto.bilibili.app.archive.v1.StaffInfo>}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getStaffInfoList = function() {
  return /** @type{!Array<!proto.bilibili.app.archive.v1.StaffInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bilibili.app.archive.v1.StaffInfo, 28));
};


/**
 * @param {!Array<!proto.bilibili.app.archive.v1.StaffInfo>} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
*/
proto.bilibili.app.archive.v1.Arc.prototype.setStaffInfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 28, value);
};


/**
 * @param {!proto.bilibili.app.archive.v1.StaffInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bilibili.app.archive.v1.StaffInfo}
 */
proto.bilibili.app.archive.v1.Arc.prototype.addStaffInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 28, opt_value, proto.bilibili.app.archive.v1.StaffInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.clearStaffInfoList = function() {
  return this.setStaffInfoList([]);
};


/**
 * optional int64 season_id = 29;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getSeasonId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 29, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setSeasonId = function(value) {
  return jspb.Message.setProto3IntField(this, 29, value);
};


/**
 * optional int64 attribute_v2 = 30;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Arc.prototype.getAttributeV2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 30, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Arc} returns this
 */
proto.bilibili.app.archive.v1.Arc.prototype.setAttributeV2 = function(value) {
  return jspb.Message.setProto3IntField(this, 30, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.archive.v1.Author.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.archive.v1.Author.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.archive.v1.Author} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Author.toObject = function(includeInstance, msg) {
  var f, obj = {
    mid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    face: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.archive.v1.Author}
 */
proto.bilibili.app.archive.v1.Author.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.archive.v1.Author;
  return proto.bilibili.app.archive.v1.Author.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.archive.v1.Author} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.archive.v1.Author}
 */
proto.bilibili.app.archive.v1.Author.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.archive.v1.Author.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.archive.v1.Author.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.archive.v1.Author} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Author.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFace();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int64 mid = 1;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Author.prototype.getMid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Author} returns this
 */
proto.bilibili.app.archive.v1.Author.prototype.setMid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Author.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Author} returns this
 */
proto.bilibili.app.archive.v1.Author.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string face = 3;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Author.prototype.getFace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Author} returns this
 */
proto.bilibili.app.archive.v1.Author.prototype.setFace = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.archive.v1.Dimension.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.archive.v1.Dimension.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.archive.v1.Dimension} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Dimension.toObject = function(includeInstance, msg) {
  var f, obj = {
    width: jspb.Message.getFieldWithDefault(msg, 1, 0),
    height: jspb.Message.getFieldWithDefault(msg, 2, 0),
    rotate: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.archive.v1.Dimension}
 */
proto.bilibili.app.archive.v1.Dimension.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.archive.v1.Dimension;
  return proto.bilibili.app.archive.v1.Dimension.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.archive.v1.Dimension} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.archive.v1.Dimension}
 */
proto.bilibili.app.archive.v1.Dimension.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWidth(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHeight(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRotate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.archive.v1.Dimension.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.archive.v1.Dimension.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.archive.v1.Dimension} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Dimension.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getRotate();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional int64 width = 1;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Dimension.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Dimension} returns this
 */
proto.bilibili.app.archive.v1.Dimension.prototype.setWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 height = 2;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Dimension.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Dimension} returns this
 */
proto.bilibili.app.archive.v1.Dimension.prototype.setHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 rotate = 3;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Dimension.prototype.getRotate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Dimension} returns this
 */
proto.bilibili.app.archive.v1.Dimension.prototype.setRotate = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.archive.v1.Page.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.archive.v1.Page.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.archive.v1.Page} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Page.toObject = function(includeInstance, msg) {
  var f, obj = {
    cid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    page: jspb.Message.getFieldWithDefault(msg, 2, 0),
    from: jspb.Message.getFieldWithDefault(msg, 3, ""),
    part: jspb.Message.getFieldWithDefault(msg, 4, ""),
    duration: jspb.Message.getFieldWithDefault(msg, 5, 0),
    vid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    desc: jspb.Message.getFieldWithDefault(msg, 7, ""),
    weblink: jspb.Message.getFieldWithDefault(msg, 8, ""),
    dimension: (f = msg.getDimension()) && proto.bilibili.app.archive.v1.Dimension.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.archive.v1.Page}
 */
proto.bilibili.app.archive.v1.Page.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.archive.v1.Page;
  return proto.bilibili.app.archive.v1.Page.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.archive.v1.Page} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.archive.v1.Page}
 */
proto.bilibili.app.archive.v1.Page.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPart(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDuration(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setVid(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDesc(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setWeblink(value);
      break;
    case 9:
      var value = new proto.bilibili.app.archive.v1.Dimension;
      reader.readMessage(value,proto.bilibili.app.archive.v1.Dimension.deserializeBinaryFromReader);
      msg.setDimension(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.archive.v1.Page.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.archive.v1.Page.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.archive.v1.Page} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Page.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPart();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDuration();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getVid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getDesc();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getWeblink();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDimension();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.bilibili.app.archive.v1.Dimension.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 cid = 1;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Page.prototype.getCid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
 */
proto.bilibili.app.archive.v1.Page.prototype.setCid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 page = 2;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Page.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
 */
proto.bilibili.app.archive.v1.Page.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string from = 3;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Page.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
 */
proto.bilibili.app.archive.v1.Page.prototype.setFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string part = 4;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Page.prototype.getPart = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
 */
proto.bilibili.app.archive.v1.Page.prototype.setPart = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 duration = 5;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Page.prototype.getDuration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
 */
proto.bilibili.app.archive.v1.Page.prototype.setDuration = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string vid = 6;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Page.prototype.getVid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
 */
proto.bilibili.app.archive.v1.Page.prototype.setVid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string desc = 7;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Page.prototype.getDesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
 */
proto.bilibili.app.archive.v1.Page.prototype.setDesc = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string webLink = 8;
 * @return {string}
 */
proto.bilibili.app.archive.v1.Page.prototype.getWeblink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
 */
proto.bilibili.app.archive.v1.Page.prototype.setWeblink = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional Dimension dimension = 9;
 * @return {?proto.bilibili.app.archive.v1.Dimension}
 */
proto.bilibili.app.archive.v1.Page.prototype.getDimension = function() {
  return /** @type{?proto.bilibili.app.archive.v1.Dimension} */ (
    jspb.Message.getWrapperField(this, proto.bilibili.app.archive.v1.Dimension, 9));
};


/**
 * @param {?proto.bilibili.app.archive.v1.Dimension|undefined} value
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
*/
proto.bilibili.app.archive.v1.Page.prototype.setDimension = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bilibili.app.archive.v1.Page} returns this
 */
proto.bilibili.app.archive.v1.Page.prototype.clearDimension = function() {
  return this.setDimension(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bilibili.app.archive.v1.Page.prototype.hasDimension = function() {
  return jspb.Message.getField(this, 9) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.archive.v1.Rights.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.archive.v1.Rights.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.archive.v1.Rights} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Rights.toObject = function(includeInstance, msg) {
  var f, obj = {
    bp: jspb.Message.getFieldWithDefault(msg, 1, 0),
    elec: jspb.Message.getFieldWithDefault(msg, 2, 0),
    download: jspb.Message.getFieldWithDefault(msg, 3, 0),
    movie: jspb.Message.getFieldWithDefault(msg, 4, 0),
    pay: jspb.Message.getFieldWithDefault(msg, 5, 0),
    hd5: jspb.Message.getFieldWithDefault(msg, 6, 0),
    noReprint: jspb.Message.getFieldWithDefault(msg, 7, 0),
    autoplay: jspb.Message.getFieldWithDefault(msg, 8, 0),
    ugcPay: jspb.Message.getFieldWithDefault(msg, 9, 0),
    isCooperation: jspb.Message.getFieldWithDefault(msg, 10, 0),
    ugcPayPreview: jspb.Message.getFieldWithDefault(msg, 11, 0),
    noBackground: jspb.Message.getFieldWithDefault(msg, 12, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.archive.v1.Rights}
 */
proto.bilibili.app.archive.v1.Rights.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.archive.v1.Rights;
  return proto.bilibili.app.archive.v1.Rights.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.archive.v1.Rights} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.archive.v1.Rights}
 */
proto.bilibili.app.archive.v1.Rights.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBp(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setElec(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDownload(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMovie(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPay(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHd5(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNoReprint(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAutoplay(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUgcPay(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsCooperation(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUgcPayPreview(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNoBackground(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.archive.v1.Rights.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.archive.v1.Rights.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.archive.v1.Rights} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Rights.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBp();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getElec();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getDownload();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getMovie();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getPay();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getHd5();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getNoReprint();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getAutoplay();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getUgcPay();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getIsCooperation();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getUgcPayPreview();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getNoBackground();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
};


/**
 * optional int32 bp = 1;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getBp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setBp = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 elec = 2;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getElec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setElec = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 download = 3;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getDownload = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setDownload = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 movie = 4;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getMovie = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setMovie = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 pay = 5;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getPay = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setPay = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 hd5 = 6;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getHd5 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setHd5 = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 no_reprint = 7;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getNoReprint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setNoReprint = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 autoplay = 8;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getAutoplay = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setAutoplay = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 ugc_pay = 9;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getUgcPay = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setUgcPay = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 is_cooperation = 10;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getIsCooperation = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setIsCooperation = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 ugc_pay_preview = 11;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getUgcPayPreview = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setUgcPayPreview = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 no_background = 12;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Rights.prototype.getNoBackground = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Rights} returns this
 */
proto.bilibili.app.archive.v1.Rights.prototype.setNoBackground = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.archive.v1.StaffInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.archive.v1.StaffInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.archive.v1.StaffInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.StaffInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    mid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    attribute: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.archive.v1.StaffInfo}
 */
proto.bilibili.app.archive.v1.StaffInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.archive.v1.StaffInfo;
  return proto.bilibili.app.archive.v1.StaffInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.archive.v1.StaffInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.archive.v1.StaffInfo}
 */
proto.bilibili.app.archive.v1.StaffInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAttribute(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.archive.v1.StaffInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.archive.v1.StaffInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.archive.v1.StaffInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.StaffInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAttribute();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional int64 mid = 1;
 * @return {number}
 */
proto.bilibili.app.archive.v1.StaffInfo.prototype.getMid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.StaffInfo} returns this
 */
proto.bilibili.app.archive.v1.StaffInfo.prototype.setMid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.bilibili.app.archive.v1.StaffInfo.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.archive.v1.StaffInfo} returns this
 */
proto.bilibili.app.archive.v1.StaffInfo.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 attribute = 3;
 * @return {number}
 */
proto.bilibili.app.archive.v1.StaffInfo.prototype.getAttribute = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.StaffInfo} returns this
 */
proto.bilibili.app.archive.v1.StaffInfo.prototype.setAttribute = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.archive.v1.Stat.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.archive.v1.Stat.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.archive.v1.Stat} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Stat.toObject = function(includeInstance, msg) {
  var f, obj = {
    aid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    view: jspb.Message.getFieldWithDefault(msg, 2, 0),
    danmaku: jspb.Message.getFieldWithDefault(msg, 3, 0),
    reply: jspb.Message.getFieldWithDefault(msg, 4, 0),
    fav: jspb.Message.getFieldWithDefault(msg, 5, 0),
    coin: jspb.Message.getFieldWithDefault(msg, 6, 0),
    share: jspb.Message.getFieldWithDefault(msg, 7, 0),
    nowRank: jspb.Message.getFieldWithDefault(msg, 8, 0),
    hisRank: jspb.Message.getFieldWithDefault(msg, 9, 0),
    like: jspb.Message.getFieldWithDefault(msg, 10, 0),
    dislike: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.archive.v1.Stat}
 */
proto.bilibili.app.archive.v1.Stat.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.archive.v1.Stat;
  return proto.bilibili.app.archive.v1.Stat.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.archive.v1.Stat} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.archive.v1.Stat}
 */
proto.bilibili.app.archive.v1.Stat.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setView(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDanmaku(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReply(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFav(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCoin(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setShare(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNowRank(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHisRank(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLike(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDislike(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.archive.v1.Stat.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.archive.v1.Stat.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.archive.v1.Stat} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.archive.v1.Stat.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getView();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getDanmaku();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getReply();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getFav();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getCoin();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getShare();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getNowRank();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getHisRank();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getLike();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getDislike();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
};


/**
 * optional int64 aid = 1;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getAid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setAid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 view = 2;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getView = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setView = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 danmaku = 3;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getDanmaku = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setDanmaku = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 reply = 4;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getReply = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setReply = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 fav = 5;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getFav = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setFav = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 coin = 6;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getCoin = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setCoin = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 share = 7;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getShare = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setShare = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 now_rank = 8;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getNowRank = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setNowRank = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 his_rank = 9;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getHisRank = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setHisRank = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 like = 10;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getLike = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setLike = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 dislike = 11;
 * @return {number}
 */
proto.bilibili.app.archive.v1.Stat.prototype.getDislike = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.archive.v1.Stat} returns this
 */
proto.bilibili.app.archive.v1.Stat.prototype.setDislike = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


goog.object.extend(exports, proto.bilibili.app.archive.v1);
