// source: bilibili/app/interfaces/v1/space.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = self;

var bilibili_app_archive_middleware_v1_preload_pb = require('../../../../proto/app/archive/middleware/v1/preload_pb.js');
goog.object.extend(proto, bilibili_app_archive_middleware_v1_preload_pb);
var bilibili_app_archive_v1_archive_pb = require('../../../../proto/app/archive/v1/archive_pb.js');
goog.object.extend(proto, bilibili_app_archive_v1_archive_pb);
var bilibili_app_dynamic_v2_dynamic_pb = require('../../../../proto/app/dynamic/v2/dynamic_pb.js');
goog.object.extend(proto, bilibili_app_dynamic_v2_dynamic_pb);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.Arc', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.Dynamic', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.From', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.OfficialVerify', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.SearchArchiveReply', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.SearchArchiveReq', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.SearchDynamicReply', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.SearchDynamicReq', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.SearchTabReply', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.SearchTabReq', null, global);
goog.exportSymbol('proto.bilibili.app.interfaces.v1.Tab', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.Arc = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.Arc, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.Arc.displayName = 'proto.bilibili.app.interfaces.v1.Arc';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.Dynamic = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.Dynamic, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.Dynamic.displayName = 'proto.bilibili.app.interfaces.v1.Dynamic';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.OfficialVerify = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.OfficialVerify, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.OfficialVerify.displayName = 'proto.bilibili.app.interfaces.v1.OfficialVerify';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.SearchTabReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bilibili.app.interfaces.v1.SearchTabReply.repeatedFields_, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.SearchTabReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.SearchTabReply.displayName = 'proto.bilibili.app.interfaces.v1.SearchTabReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.SearchTabReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.SearchTabReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.SearchTabReq.displayName = 'proto.bilibili.app.interfaces.v1.SearchTabReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bilibili.app.interfaces.v1.SearchArchiveReply.repeatedFields_, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.SearchArchiveReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.SearchArchiveReply.displayName = 'proto.bilibili.app.interfaces.v1.SearchArchiveReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.SearchArchiveReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.SearchArchiveReq.displayName = 'proto.bilibili.app.interfaces.v1.SearchArchiveReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bilibili.app.interfaces.v1.SearchDynamicReply.repeatedFields_, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.SearchDynamicReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.SearchDynamicReply.displayName = 'proto.bilibili.app.interfaces.v1.SearchDynamicReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.SearchDynamicReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.SearchDynamicReq.displayName = 'proto.bilibili.app.interfaces.v1.SearchDynamicReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bilibili.app.interfaces.v1.Tab = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bilibili.app.interfaces.v1.Tab, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bilibili.app.interfaces.v1.Tab.displayName = 'proto.bilibili.app.interfaces.v1.Tab';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.Arc.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.Arc.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.Arc} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.Arc.toObject = function(includeInstance, msg) {
  var f, obj = {
    archive: (f = msg.getArchive()) && bilibili_app_archive_v1_archive_pb.Arc.toObject(includeInstance, f),
    uri: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.Arc}
 */
proto.bilibili.app.interfaces.v1.Arc.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.Arc;
  return proto.bilibili.app.interfaces.v1.Arc.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.Arc} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.Arc}
 */
proto.bilibili.app.interfaces.v1.Arc.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bilibili_app_archive_v1_archive_pb.Arc;
      reader.readMessage(value,bilibili_app_archive_v1_archive_pb.Arc.deserializeBinaryFromReader);
      msg.setArchive(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.Arc.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.Arc.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.Arc} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.Arc.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArchive();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bilibili_app_archive_v1_archive_pb.Arc.serializeBinaryToWriter
    );
  }
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bilibili.app.archive.v1.Arc archive = 1;
 * @return {?proto.bilibili.app.archive.v1.Arc}
 */
proto.bilibili.app.interfaces.v1.Arc.prototype.getArchive = function() {
  return /** @type{?proto.bilibili.app.archive.v1.Arc} */ (
    jspb.Message.getWrapperField(this, bilibili_app_archive_v1_archive_pb.Arc, 1));
};


/**
 * @param {?proto.bilibili.app.archive.v1.Arc|undefined} value
 * @return {!proto.bilibili.app.interfaces.v1.Arc} returns this
*/
proto.bilibili.app.interfaces.v1.Arc.prototype.setArchive = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bilibili.app.interfaces.v1.Arc} returns this
 */
proto.bilibili.app.interfaces.v1.Arc.prototype.clearArchive = function() {
  return this.setArchive(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bilibili.app.interfaces.v1.Arc.prototype.hasArchive = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string uri = 2;
 * @return {string}
 */
proto.bilibili.app.interfaces.v1.Arc.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.interfaces.v1.Arc} returns this
 */
proto.bilibili.app.interfaces.v1.Arc.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.Dynamic.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.Dynamic.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.Dynamic} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.Dynamic.toObject = function(includeInstance, msg) {
  var f, obj = {
    dynamic: (f = msg.getDynamic()) && bilibili_app_dynamic_v2_dynamic_pb.DynamicItem.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.Dynamic}
 */
proto.bilibili.app.interfaces.v1.Dynamic.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.Dynamic;
  return proto.bilibili.app.interfaces.v1.Dynamic.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.Dynamic} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.Dynamic}
 */
proto.bilibili.app.interfaces.v1.Dynamic.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bilibili_app_dynamic_v2_dynamic_pb.DynamicItem;
      reader.readMessage(value,bilibili_app_dynamic_v2_dynamic_pb.DynamicItem.deserializeBinaryFromReader);
      msg.setDynamic(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.Dynamic.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.Dynamic.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.Dynamic} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.Dynamic.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDynamic();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bilibili_app_dynamic_v2_dynamic_pb.DynamicItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional bilibili.app.dynamic.v2.DynamicItem dynamic = 1;
 * @return {?proto.bilibili.app.dynamic.v2.DynamicItem}
 */
proto.bilibili.app.interfaces.v1.Dynamic.prototype.getDynamic = function() {
  return /** @type{?proto.bilibili.app.dynamic.v2.DynamicItem} */ (
    jspb.Message.getWrapperField(this, bilibili_app_dynamic_v2_dynamic_pb.DynamicItem, 1));
};


/**
 * @param {?proto.bilibili.app.dynamic.v2.DynamicItem|undefined} value
 * @return {!proto.bilibili.app.interfaces.v1.Dynamic} returns this
*/
proto.bilibili.app.interfaces.v1.Dynamic.prototype.setDynamic = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bilibili.app.interfaces.v1.Dynamic} returns this
 */
proto.bilibili.app.interfaces.v1.Dynamic.prototype.clearDynamic = function() {
  return this.setDynamic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bilibili.app.interfaces.v1.Dynamic.prototype.hasDynamic = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.OfficialVerify.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.OfficialVerify} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    desc: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.OfficialVerify}
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.OfficialVerify;
  return proto.bilibili.app.interfaces.v1.OfficialVerify.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.OfficialVerify} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.OfficialVerify}
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDesc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.OfficialVerify.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.OfficialVerify} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getDesc();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 type = 1;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.OfficialVerify} returns this
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.prototype.setType = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string desc = 2;
 * @return {string}
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.prototype.getDesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.interfaces.v1.OfficialVerify} returns this
 */
proto.bilibili.app.interfaces.v1.OfficialVerify.prototype.setDesc = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.SearchTabReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.SearchTabReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    focus: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tabsList: jspb.Message.toObjectList(msg.getTabsList(),
    proto.bilibili.app.interfaces.v1.Tab.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReply}
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.SearchTabReply;
  return proto.bilibili.app.interfaces.v1.SearchTabReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.SearchTabReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReply}
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFocus(value);
      break;
    case 2:
      var value = new proto.bilibili.app.interfaces.v1.Tab;
      reader.readMessage(value,proto.bilibili.app.interfaces.v1.Tab.deserializeBinaryFromReader);
      msg.addTabs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.SearchTabReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.SearchTabReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFocus();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getTabsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.bilibili.app.interfaces.v1.Tab.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 focus = 1;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.prototype.getFocus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReply} returns this
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.prototype.setFocus = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated Tab tabs = 2;
 * @return {!Array<!proto.bilibili.app.interfaces.v1.Tab>}
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.prototype.getTabsList = function() {
  return /** @type{!Array<!proto.bilibili.app.interfaces.v1.Tab>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bilibili.app.interfaces.v1.Tab, 2));
};


/**
 * @param {!Array<!proto.bilibili.app.interfaces.v1.Tab>} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReply} returns this
*/
proto.bilibili.app.interfaces.v1.SearchTabReply.prototype.setTabsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.bilibili.app.interfaces.v1.Tab=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bilibili.app.interfaces.v1.Tab}
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.prototype.addTabs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.bilibili.app.interfaces.v1.Tab, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReply} returns this
 */
proto.bilibili.app.interfaces.v1.SearchTabReply.prototype.clearTabsList = function() {
  return this.setTabsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.SearchTabReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.SearchTabReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    keyword: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    from: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReq}
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.SearchTabReq;
  return proto.bilibili.app.interfaces.v1.SearchTabReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.SearchTabReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReq}
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKeyword(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFrom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.SearchTabReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.SearchTabReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKeyword();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getFrom();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string keyword = 1;
 * @return {string}
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.prototype.getKeyword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.prototype.setKeyword = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 mid = 2;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.prototype.getMid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.prototype.setMid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 from = 3;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.prototype.getFrom = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchTabReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchTabReq.prototype.setFrom = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.SearchArchiveReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.SearchArchiveReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    archivesList: jspb.Message.toObjectList(msg.getArchivesList(),
    proto.bilibili.app.interfaces.v1.Arc.toObject, includeInstance),
    total: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReply}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.SearchArchiveReply;
  return proto.bilibili.app.interfaces.v1.SearchArchiveReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.SearchArchiveReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReply}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bilibili.app.interfaces.v1.Arc;
      reader.readMessage(value,proto.bilibili.app.interfaces.v1.Arc.deserializeBinaryFromReader);
      msg.addArchives(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTotal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.SearchArchiveReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.SearchArchiveReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArchivesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.bilibili.app.interfaces.v1.Arc.serializeBinaryToWriter
    );
  }
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * repeated Arc archives = 1;
 * @return {!Array<!proto.bilibili.app.interfaces.v1.Arc>}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.prototype.getArchivesList = function() {
  return /** @type{!Array<!proto.bilibili.app.interfaces.v1.Arc>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bilibili.app.interfaces.v1.Arc, 1));
};


/**
 * @param {!Array<!proto.bilibili.app.interfaces.v1.Arc>} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReply} returns this
*/
proto.bilibili.app.interfaces.v1.SearchArchiveReply.prototype.setArchivesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bilibili.app.interfaces.v1.Arc=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bilibili.app.interfaces.v1.Arc}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.prototype.addArchives = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bilibili.app.interfaces.v1.Arc, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReply} returns this
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.prototype.clearArchivesList = function() {
  return this.setArchivesList([]);
};


/**
 * optional int64 total = 2;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReply} returns this
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReply.prototype.setTotal = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.SearchArchiveReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.SearchArchiveReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    keyword: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pn: jspb.Message.getFieldWithDefault(msg, 3, 0),
    ps: jspb.Message.getFieldWithDefault(msg, 4, 0),
    playerArgs: (f = msg.getPlayerArgs()) && bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReq}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.SearchArchiveReq;
  return proto.bilibili.app.interfaces.v1.SearchArchiveReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.SearchArchiveReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReq}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKeyword(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPn(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPs(value);
      break;
    case 5:
      var value = new bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs;
      reader.readMessage(value,bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs.deserializeBinaryFromReader);
      msg.setPlayerArgs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.SearchArchiveReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.SearchArchiveReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKeyword();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getPn();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getPs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getPlayerArgs();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs.serializeBinaryToWriter
    );
  }
};


/**
 * optional string keyword = 1;
 * @return {string}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.getKeyword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.setKeyword = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 mid = 2;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.getMid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.setMid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 pn = 3;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.getPn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.setPn = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 ps = 4;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.getPs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.setPs = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bilibili.app.archive.middleware.v1.PlayerArgs player_args = 5;
 * @return {?proto.bilibili.app.archive.middleware.v1.PlayerArgs}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.getPlayerArgs = function() {
  return /** @type{?proto.bilibili.app.archive.middleware.v1.PlayerArgs} */ (
    jspb.Message.getWrapperField(this, bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs, 5));
};


/**
 * @param {?proto.bilibili.app.archive.middleware.v1.PlayerArgs|undefined} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReq} returns this
*/
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.setPlayerArgs = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bilibili.app.interfaces.v1.SearchArchiveReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.clearPlayerArgs = function() {
  return this.setPlayerArgs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bilibili.app.interfaces.v1.SearchArchiveReq.prototype.hasPlayerArgs = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.SearchDynamicReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.SearchDynamicReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    dynamicsList: jspb.Message.toObjectList(msg.getDynamicsList(),
    proto.bilibili.app.interfaces.v1.Dynamic.toObject, includeInstance),
    total: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReply}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.SearchDynamicReply;
  return proto.bilibili.app.interfaces.v1.SearchDynamicReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.SearchDynamicReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReply}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bilibili.app.interfaces.v1.Dynamic;
      reader.readMessage(value,proto.bilibili.app.interfaces.v1.Dynamic.deserializeBinaryFromReader);
      msg.addDynamics(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTotal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.SearchDynamicReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.SearchDynamicReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDynamicsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.bilibili.app.interfaces.v1.Dynamic.serializeBinaryToWriter
    );
  }
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * repeated Dynamic dynamics = 1;
 * @return {!Array<!proto.bilibili.app.interfaces.v1.Dynamic>}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.prototype.getDynamicsList = function() {
  return /** @type{!Array<!proto.bilibili.app.interfaces.v1.Dynamic>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bilibili.app.interfaces.v1.Dynamic, 1));
};


/**
 * @param {!Array<!proto.bilibili.app.interfaces.v1.Dynamic>} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReply} returns this
*/
proto.bilibili.app.interfaces.v1.SearchDynamicReply.prototype.setDynamicsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bilibili.app.interfaces.v1.Dynamic=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bilibili.app.interfaces.v1.Dynamic}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.prototype.addDynamics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bilibili.app.interfaces.v1.Dynamic, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReply} returns this
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.prototype.clearDynamicsList = function() {
  return this.setDynamicsList([]);
};


/**
 * optional int64 total = 2;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReply} returns this
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReply.prototype.setTotal = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.SearchDynamicReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.SearchDynamicReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    keyword: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pn: jspb.Message.getFieldWithDefault(msg, 3, 0),
    ps: jspb.Message.getFieldWithDefault(msg, 4, 0),
    playerArgs: (f = msg.getPlayerArgs()) && bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReq}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.SearchDynamicReq;
  return proto.bilibili.app.interfaces.v1.SearchDynamicReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.SearchDynamicReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReq}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKeyword(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPn(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPs(value);
      break;
    case 5:
      var value = new bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs;
      reader.readMessage(value,bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs.deserializeBinaryFromReader);
      msg.setPlayerArgs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.SearchDynamicReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.SearchDynamicReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKeyword();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getPn();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getPs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getPlayerArgs();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs.serializeBinaryToWriter
    );
  }
};


/**
 * optional string keyword = 1;
 * @return {string}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.getKeyword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.setKeyword = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 mid = 2;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.getMid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.setMid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 pn = 3;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.getPn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.setPn = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 ps = 4;
 * @return {number}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.getPs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.setPs = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bilibili.app.archive.middleware.v1.PlayerArgs player_args = 5;
 * @return {?proto.bilibili.app.archive.middleware.v1.PlayerArgs}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.getPlayerArgs = function() {
  return /** @type{?proto.bilibili.app.archive.middleware.v1.PlayerArgs} */ (
    jspb.Message.getWrapperField(this, bilibili_app_archive_middleware_v1_preload_pb.PlayerArgs, 5));
};


/**
 * @param {?proto.bilibili.app.archive.middleware.v1.PlayerArgs|undefined} value
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReq} returns this
*/
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.setPlayerArgs = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bilibili.app.interfaces.v1.SearchDynamicReq} returns this
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.clearPlayerArgs = function() {
  return this.setPlayerArgs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bilibili.app.interfaces.v1.SearchDynamicReq.prototype.hasPlayerArgs = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bilibili.app.interfaces.v1.Tab.prototype.toObject = function(opt_includeInstance) {
  return proto.bilibili.app.interfaces.v1.Tab.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bilibili.app.interfaces.v1.Tab} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.Tab.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uri: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bilibili.app.interfaces.v1.Tab}
 */
proto.bilibili.app.interfaces.v1.Tab.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bilibili.app.interfaces.v1.Tab;
  return proto.bilibili.app.interfaces.v1.Tab.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bilibili.app.interfaces.v1.Tab} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bilibili.app.interfaces.v1.Tab}
 */
proto.bilibili.app.interfaces.v1.Tab.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bilibili.app.interfaces.v1.Tab.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bilibili.app.interfaces.v1.Tab.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bilibili.app.interfaces.v1.Tab} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bilibili.app.interfaces.v1.Tab.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.bilibili.app.interfaces.v1.Tab.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.interfaces.v1.Tab} returns this
 */
proto.bilibili.app.interfaces.v1.Tab.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string uri = 2;
 * @return {string}
 */
proto.bilibili.app.interfaces.v1.Tab.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bilibili.app.interfaces.v1.Tab} returns this
 */
proto.bilibili.app.interfaces.v1.Tab.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.bilibili.app.interfaces.v1.From = {
  ARCHIVETAB: 0,
  DYNAMICTAB: 1
};

goog.object.extend(exports, proto.bilibili.app.interfaces.v1);
